# app.yaml
runtime: custom
env: standard
service: default
automatic_scaling:
  min_num_instances: automatic
  max_num_instances: automatic
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10